<div dir="rtl">

# فصل ۲: گسترش پایتون با استفاده از NumPy

## NumPy چیست؟

در پایتون، معمولاً از نوع داده `list` برای ذخیره مجموعه‌ای از آیتم‌ها استفاده می‌کنید. لیست پایتون مشابه مفهوم آرایه در زبان‌هایی مثل جاوا، سی‌شارپ و جاوااسکریپت است.

</div>

In [ ]:
list1 = [1,2,3,4,5]

<div dir="rtl">

برخلاف آرایه‌ها، یک لیست پایتون نیازی ندارد که عناصر آن از یک نوع باشند. مثال زیر یک لیست کاملاً قانونی در پایتون است:

</div>

In [ ]:
list2 = [1,"Hello",3.14,True,5]

<div dir="rtl">

در حالی که این ویژگی منحصربه‌فرد در پایتون انعطاف‌پذیری را هنگام کار با انواع مختلف داده در یک لیست فراهم می‌کند، اما معایبی هم دارد، به‌ویژه هنگام پردازش حجم زیادی از داده (که در پروژه‌های یادگیری ماشین و علم داده رایج است). مشکل اصلی نوع داده لیست در پایتون، کارایی آن است. برای اینکه یک لیست بتواند آیتم‌هایی با انواع غیریکسان داشته باشد، هر آیتم در یک مکان حافظه ذخیره می‌شود و لیست شامل یک "آرایه" از اشاره‌گرها به هر یک از این مکان‌هاست. یک لیست پایتون به موارد زیر نیاز دارد:

- حداقل ۴ بایت برای هر اشاره‌گر
- حداقل ۱۶ بایت برای کوچکترین شیء پایتون - ۴ بایت برای اشاره‌گر، ۴ بایت برای شمارش مراجع، ۴ بایت برای مقدار. همه اینها با هم به ۱۶ بایت می‌رسند.

به دلیل نحوه پیاده‌سازی لیست در پایتون، دسترسی به آیتم‌ها در یک لیست بزرگ از نظر محاسباتی پرهزینه است. برای حل این محدودیت در ویژگی لیست پایتون، برنامه‌نویسان پایتون به NumPy روی می‌آورند، یک افزونه برای زبان برنامه‌نویسی پایتون که پشتیبانی از آرایه‌ها و ماتریس‌های بزرگ چندبعدی را به همراه کتابخانه بزرگی از توابع ریاضی سطح بالا برای کار بر روی این آرایه‌ها اضافه می‌کند.

در NumPy، یک آرایه از نوع `ndarray` (آرایه n بعدی) است و همه عناصر باید از یک نوع باشند. یک شیء `ndarray` یک آرایه همگن چندبعدی از آیتم‌های با اندازه ثابت را نشان می‌دهد و بسیار کارآمدتر از لیست پایتون است. شیء `ndarray` همچنین توابعی را فراهم می‌کند که بر روی کل آرایه به طور همزمان عمل می‌کنند.

---

## ایجاد آرایه‌های NumPy

قبل از استفاده از NumPy، ابتدا باید بسته NumPy را وارد کنید (می‌توانید از نام مستعار مرسوم `np` استفاده کنید):

</div>

In [ ]:
import numpy as np

<div dir="rtl">

اولین راه برای ساخت آرایه‌های NumPy، ایجاد ذاتی آنها با استفاده از توابعی است که در خود NumPy تعبیه شده‌اند. ابتدا می‌توانید از تابع `arange()` برای ایجاد یک آرایه با فواصل مساوی و گام مشخص استفاده کنید:

</div>

In [ ]:
a1 = np.arange(10)        # creates a range from 0 to 9
print(a1)                 # [0 1 2 3 4 5 6 7 8 9]
print(a1.shape)           # (10,)


<div dir="rtl">

عبارت بالا یک آرایه رتبه ۱ (یک‌بعدی) از ده عنصر ایجاد می‌کند. برای دریافت شکل آرایه، از ویژگی `shape` استفاده کنید. می‌توانید `a1` را به عنوان یک ماتریس ۱۰×۱ در نظر بگیرید.

همچنین می‌توانید یک گام در تابع `arange()` مشخص کنید. قطعه کد زیر یک مقدار گام ۲ را وارد می‌کند:

</div>

In [ ]:
a2 = np.arange(0,10,2)    # creates a range from 0 to 9, step 2
print(a2)                 # [0 2 4 6 8]


<div dir="rtl">

برای ایجاد یک آرایه با اندازه مشخص پر از ۰، از تابع `zeros()` استفاده کنید:

</div>

In [ ]:
a3 = np.zeros(5)          # create an array with all 0s
print(a3)                 # [ 0.  0.  0.  0.  0.]
print(a3.shape)           # (5,)


<div dir="rtl">

همچنین می‌توانید آرایه‌های دو بعدی را با استفاده از تابع `zeros()` ایجاد کنید:

</div>

In [ ]:
a4 = np.zeros((2,3))      # array of rank 2 with all 0s; 2 rows and 3 columns
print(a4.shape)           # (2,3)
print(a4)

<div dir="rtl">

اگر آرایه‌ای پر از یک عدد خاص به جای ۰ می‌خواهید، از تابع `full()` استفاده کنید:

</div>

In [ ]:
a5 = np.full((3,3), 8)    # array of rank 2 with all 8s
print(a5)


<div dir="rtl">

گاهی اوقات نیاز دارید آرایه‌ای ایجاد کنید که شبیه ماتریس همانی باشد. در NumPy، می‌توانید این کار را با استفاده از تابع `eye()` انجام دهید:

</div>

In [ ]:
a6 = np.eye(5)            # 4x4 identity matrix
print(a6)
print(a6.shape)


<div dir="rtl">

تابع `eye()` یک آرایه دو بعدی با یک‌ها روی قطر اصلی و صفرها در جاهای دیگر برمی‌گرداند.

برای ایجاد یک آرایه پر از اعداد تصادفی، می‌توانید از تابع `random()` از ماژول `numpy.random` استفاده کنید:

</div>

In [ ]:
a7 = np.random.random((3,4)) # rank 2 array (2 rows 4 columns) with random values
                             # in the half-open interval [0.0, 1.0)
print(a7)


<div dir="rtl">

راه دیگر برای ایجاد یک آرایه NumPy، ایجاد آن از یک لیست پایتون است:

</div>

In [ ]:
list1 = [1,2,3,4,5] 
list2 = [3,4,5,6,7]
r1 = np.array([list1,list2]) 
print(r1)            
print(r1.shape)


<div dir="rtl">

آرایه ایجاد شده در این مثال یک آرایه رتبه ۲ است.

---

## نمایه‌گذاری آرایه‌ها (Array Indexing)

دسترسی به عناصر در آرایه مشابه دسترسی به عناصر در یک لیست پایتون است:

</div>

In [ ]:
print(r1)
print(r1.shape)

In [ ]:
print(r1[0][0])   # 1
print(r1[1])      # [3 4 5 6 7]

print(r1[-1])     # [3 4 5 6 7]
print(r1[-2])     # [1 2 3 4 5]



<div dir="rtl">

قطعه کد زیر آرایه دیگری به نام `r2` ایجاد می‌کند که دو بعدی است:

</div>

In [ ]:
list2 = [6,7,8,9,0]
r2 = np.array([list1,list2])  # rank 2 array
print(r2)
print(r2.shape)               # (2,5) - 2 rows and 5 columns
print(r2[0,0])                # 1
print(r2[0,1])                # 2
print(r2[1,0])                # 6


In [ ]:
print(r2[1,3])

<div dir="rtl">

در اینجا، `r2` یک آرایه رتبه ۲ با دو سطر و پنج ستون است.

علاوه بر استفاده از یک اندیس برای دسترسی به عناصر در یک آرایه، می‌توانید از یک لیست نیز به عنوان اندیس استفاده کنید:

</div>

In [ ]:
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1[[2,4]])              # [3 5]


<div dir="rtl">

---

## نمایه‌گذاری بولی (Boolean Indexing)

علاوه بر استفاده از نمایه‌گذاری برای دسترسی به عناصر در یک آرایه، روش بسیار جالب دیگری برای دسترسی به عناصر در یک آرایه NumPy وجود دارد. به مثال زیر توجه کنید:

</div>

In [ ]:
print(r1)
print(r1>2)     # [False False  True  True  True]

<div dir="rtl">

این دستور یک لیست حاوی مقادیر بولی چاپ می‌کند. کاری که انجام می‌دهد این است که به هر عنصر در `r1` رفته و بررسی می‌کند که آیا هر عنصر بزرگتر از دو است یا خیر. نتیجه یک مقدار بولی است و یک لیست از مقادیر بولی در پایان این فرآیند ایجاد می‌شود. می‌توانید نتایج لیست را به عنوان اندیس به آرایه بازگردانید:

</div>

In [ ]:
print(r1[r1>2])    # [3 4 5]
print(r1[r1<=4])


<div dir="rtl">

این روش دسترسی به عناصر در یک آرایه به عنوان **نمایه‌گذاری بولی** شناخته می‌شود. این روش بسیار مفید است. مثال زیر را در نظر بگیرید:

</div>

In [ ]:
nums = np.arange(20)
print(nums)        # [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


<div dir="rtl">

اگر بخواهید تمام اعداد فرد را از لیست بازیابی کنید، می‌توانید به سادگی از نمایه‌گذاری بولی استفاده کنید:

</div>

In [ ]:
odd_num = nums[nums % 2 == 1]
print(odd_num)     # [ 1  3  5  7  9 11 13 15 17 19]


<div dir="rtl">

---

## برش آرایه‌ها (Slicing Arrays)

برش در آرایه‌های NumPy مشابه نحوه کار آن با لیست پایتون است. مثال زیر را در نظر بگیرید:

</div>

In [ ]:
a = np.array([[1,2,3,4,5],
               [4,5,6,7,8],
               [9,8,7,6,5],
               ])    # rank 2 array5
print(a)


<div dir="rtl">

برای استخراج دو سطر آخر و دو ستون اول، می‌توانید از برش استفاده کنید:

</div>

In [ ]:
b1 = a[1:3, :3]                 # row 1 to 3 (not inclusive) and first 3 columns
print(b1)


<div dir="rtl">

بیایید این کد را تجزیه و تحلیل کنیم. 
برش دارای نحو زیر است:
 `[start:stop]`.
  برای آرایه‌های دو بعدی، نحو برش به
   `[start:stop, start:stop]` 
   تبدیل می‌شود.
    `start:stop` 
    قبل از کاما به سطرها اشاره دارد و 
    `start:stop` 
    بعد از کاما به ستون‌ها اشاره دارد. بنابراین برای 
    `[1:4, :3]`، 
    این به این معنی است که می‌خواهید سطرهای با اندیس ۱ تا ۳ (غیرشامل ۴) و ستون‌ها از اولین ستون تا اندیس ۳ (غیرشامل) را استخراج کنید.


<center>
<img src="image1.png" width="500" alt="شکل ۲-۱: نوشتن اندیس برای سطر و ستون بین اعداد"/>
<br>
<em>شکل ۲-۱: نوشتن اندیس برای سطر و ستون بین اعداد</em>
</center>


### برش با اندیس منفی

در مورد اندیس‌های منفی چطور؟ به عنوان مثال، کد زیر را در نظر بگیرید:

</div>

In [ ]:
print(a)
b2 = a[-2:-1,-2:]
print(b2)


<div dir="rtl">

در اینجا `a[-2:-1, -2:]` به این معنی است که سطرهای با اندیس ۲- تا ۱- (غیرشامل) و ستون‌های با اندیس ۲- به بعد را استخراج می‌کنیم.

---

## برش NumPy یک مرجع است (Reference)

قابل توجه است که نتیجه یک برش NumPy یک **مرجع** است و نه یک کپی از آرایه اصلی. به مثال زیر توجه کنید:

</div>

In [ ]:
b3 = a[1:, 2:]      # row 1 onwards and column 2 onwards
                    # b3 is now pointing to a subset of a7
print(b3)


<div dir="rtl">

در اینجا، `b3` در واقع یک مرجع به آرایه اصلی `a` است.

بنابراین، اگر یکی از عناصر را در `b3` تغییر دهید:

</div>

In [ ]:
b3[0,2] = 88         # b3[0,2] is pointing to a[1,4]; modifying it will modify
                     # the original array
print(a)


<div dir="rtl">

نتیجه بر محتوای `a` تأثیر می‌گذارد.

نکته مهم دیگر این است که نتیجه برش بستگی به نحوه برش زدن شما دارد. در اینجا یک مثال آورده شده است:

</div>

In [ ]:
b4 = a[2:, :]        # row 2 onwards and all columns
print(b4)            # b4 is rank 2
print(b4.shape)


In [ ]:
b5 = a[2, :]         # row 2 and all columns
print(b5)            # b5 is rank 1


In [ ]:
print(b5.shape)      # (5,)


<div dir="rtl">

... آنگاه نتیجه یک آرایه رتبه ۱ خواهد بود.

---

# تغییر شکل آرایه‌ها (Reshaping Arrays)

می‌توانید یک آرایه را به بعد دیگری با استفاده از تابع `reshape()` تغییر شکل دهید. با استفاده از مثال `b5` (که یک آرایه رتبه ۱ است)، می‌توانید آن را به یک آرایه رتبه ۲ به صورت زیر تغییر شکل دهید:

</div>

In [ ]:
b5 = b5.reshape(1,-1)
print(b5)


: 

<div dir="rtl">

در این مثال، تابع `reshape()` را با دو آرگومان فراخوانی می‌کنید. اولین `1` نشان می‌دهد که می‌خواهید آن را به آرایه رتبه ۲ با ۱ سطر تبدیل کنید، و `1-` نشان می‌دهد که تعیین تعداد ستون‌ها را به تابع `reshape()` واگذار می‌کنید. البته، در این مثال واضح است که پس از تغییر شکل، پنج ستون وجود خواهد داشت، بنابراین می‌توانید تابع `reshape()` را به صورت `reshape(1,5)` فراخوانی کنید. با این حال، در موارد پیچیده‌تر، همیشه راحت است که بتوانید از `1-` استفاده کنید تا تابع تصمیم بگیرد که چه تعداد سطر یا ستون ایجاد کند.

در اینجا مثال دیگری از نحوه تغییر شکل `b4` (که یک آرایه رتبه ۲ است) به رتبه ۱ آورده شده است:

</div>

In [ ]:
print(b4)
b4.reshape(-1,)


<div dir="rtl">

`1-` نشان می‌دهد که اجازه می‌دهید تابع تصمیم بگیرد چه تعداد سطر ایجاد کند، تا زمانی که نتیجه نهایی یک آرایه رتبه ۱ باشد.

**نکته:** برای تبدیل یک آرایه رتبه ۲ به آرایه رتبه ۱، می‌توانید از توابع `flatten()` یا `ravel()` نیز استفاده کنید. تابع `flatten()` همیشه یک کپی از آرایه را برمی‌گرداند، در حالی که توابع `ravel()` و `reshape()` یک نمای (مرجع) از آرایه اصلی را برمی‌گردانند.

---

# محاسبات ریاضی آرایه‌ها (Array Math)

می‌توانید محاسبات ریاضی آرایه را به راحتی روی آرایه‌های NumPy انجام دهید. دو آرایه رتبه ۲ زیر را در نظر بگیرید:

</div>

In [93]:
x1 = np.array([[1,2,3],[4,5,6]])
y1 = np.array([[7,8,9],[2,3,4]])

print(x1 + y1)


[[ 8 10 12]
 [ 6  8 10]]


<div dir="rtl">

برای جمع این دو آرایه، از عملگر `+` استفاده می‌کنید. نتیجه، جمع هر عنصر متناظر در دو آرایه است.

محاسبات ریاضی آرایه مهم است، زیرا می‌توان از آن برای انجام محاسبات برداری استفاده کرد. یک مثال خوب به شرح زیر است:

</div>

In [94]:
x = np.array([2,3])
y = np.array([4,2])
z = x + y
print(z)


[6 5]


<div dir="rtl">

علاوه بر استفاده از عملگر `+`، می‌توانید از تابع `np.add()` نیز برای جمع دو آرایه استفاده کنید:

</div>

In [96]:
z_1 = np.add(x,y)
print(z_1)


[6 5]


<div dir="rtl">

علاوه بر جمع، می‌توانید تفریق، ضرب و تقسیم را نیز با آرایه‌های NumPy انجام دهید:

</div>

In [97]:
print(x1)
print(y1)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [2 3 4]]


In [98]:
print(x1 - y1)     # same as np.subtract(x1,y1)
print(x1 * y1)     # same as np.multiply(x1,y1)
print(x1 / y1)     # same as np.divide(x1,y1)


[[-6 -6 -6]
 [ 2  2  2]]
[[ 7 16 27]
 [ 8 15 24]]
[[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]]


<div dir="rtl">

کاربرد عملی توانایی ضرب یا تقسیم دو آرایه چیست؟ به عنوان مثال، فرض کنید سه آرایه دارید: یکی شامل 
نام  افراد، دیگری شامل قدهای متناظر این افراد، و آخری شامل وزن‌های متناظر افراد در گروه:

</div>

In [99]:
names   = np.array(['Ann','Joe','Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

bmi = weights/heights **2            # calculate the BMI
print(bmi)                           # [ 28.88888889  14.51836889  23.046875  ]


[28.88888889 14.51836889 23.046875  ]


<div dir="rtl">

با استفاده از تقسیم آرایه، می‌توانید به سادگی BMI را با استفاده از عبارت بالا محاسبه کنید. پیدا کردن افرادی که اضافه وزن دارند، کمبود وزن دارند یا سالم هستند، اکنون بسیار آسان است:

</div>

In [100]:
print("Overweight: "  , names[bmi>25])                    # Overweight:  ['Ann']
print("Underweight: " , names[bmi<18.5])                  # Underweight:  ['Joe']
print("Healthy: "     , names[(bmi>=18.5) & (bmi<=25)])   # Healthy:  ['Mark']


Overweight:  ['Ann']
Underweight:  ['Joe']
Healthy:  ['Mark']


<div dir="rtl">

---

# ضرب نقطه‌ای (Dot Product)

توجه داشته باشید که وقتی دو آرایه را ضرب می‌کنید، در واقع هر یک از عناصر متناظر را در دو آرایه ضرب می‌کنید. اغلب اوقات، می‌خواهید یک ضرب اسکالر (که معمولاً به عنوان ضرب نقطه‌ای نیز شناخته می‌شود) انجام دهید. ضرب نقطه‌ای یک عملیات جبری است که دو بردار هم‌بعد را گرفته و یک عدد واحد را برمی‌گرداند. ضرب نقطه‌ای دو بردار با ضرب درایه های متناظر در هر بردار و جمع همه آن محصولات محاسبه می‌شود. به عنوان مثال، با دو بردار \(a = [a_1, a_2, ..., a_n]\) و \(b = [b_1, b_2, ..., b_n]\)، ضرب نقطه‌ای این دو بردار \(a_1b_1 + a_2b_2 + ... + a_nb_n\) است.

در NumPy، ضرب نقطه‌ای با استفاده از تابع `dot()` انجام می‌شود:

</div>

In [101]:
x = np.array([2,3])
y = np.array([4,2])
np.dot(x,y)  # 2x4 + 3x2 = 14 


np.int64(14)

<div dir="rtl">

ضرب نقطه‌ای روی آرایه‌های رتبه ۲ نیز کار می‌کند. اگر ضرب نقطه‌ای دو آرایه رتبه ۲ را انجام دهید، معادل ضرب ماتریس‌ها است:

</div>

In [105]:
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[7,8],[9,10], [11,12]])
print(np.dot(x2,y2))                     # matrix multiplication


[[ 58  64]
 [139 154]]


<div dir="rtl">

---

## ماتریس (Matrix)

NumPy علاوه بر آرایه‌ها (`ndarray`)، کلاس دیگری به نام `matrix` نیز ارائه می‌دهد. کلاس `matrix` یک زیرکلاس از `ndarray` است و اساساً با `ndarray` یکسان است، با یک استثنای قابل توجه - یک ماتریس کاملاً دو بعدی است، در حالی که یک `ndarray` می‌تواند چندبعدی باشد. ایجاد یک شیء ماتریس مشابه ایجاد یک آرایه NumPy است:

</div>

In [107]:
x2 = np.matrix([[1,2],[4,5]])
y2 = np.matrix([[7,8],[2,3]])
print(x2)
print(y2)


[[1 2]
 [4 5]]
[[7 8]
 [2 3]]


<div dir="rtl">

همچنین می‌توانید یک آرایه NumPy را با استفاده از تابع `asmatrix()` به ماتریس تبدیل کنید:

</div>

In [109]:
x1 = np.array([[1,2],[4,5]])
y1 = np.array([[7,8],[2,3]])
x1 = np.asmatrix(x1)
y1 = np.asmatrix(y1)
print(type(x1))



<class 'numpy.matrix'>


<div dir="rtl">

تفاوت مهم دیگر بین یک `ndarray` و یک `matrix` زمانی رخ می‌دهد که ضرب را روی آنها انجام می‌دهید. هنگام ضرب دو شیء `ndarray`، نتیجه ضرب عنصر به عنصر است که قبلاً دیدیم. از سوی دیگر، هنگام ضرب دو شیء `matrix`، نتیجه ضرب نقطه‌ای (معادل تابع `np.dot()`) است:

</div>

In [110]:
x1 = np.array([[1,2],[4,5]])
y1 = np.array([[7,8],[2,3]])
print(x1 * y1)     # element-by-element multiplication

x2 = np.matrix([[1,2],[4,5]])
y2 = np.matrix([[7,8],[2,3]])
print(x2 * y2)    # dot product; same as np.dot()


[[ 7 16]
 [ 8 15]]
[[11 14]
 [38 47]]


<div dir="rtl">

---

## مجموع تجمعی (Cumulative Sum)

اغلب اوقات، هنگام کار با داده‌های عددی، نیاز به یافتن مجموع تجمعی اعداد در یک آرایه NumPy وجود دارد. آرایه زیر را در نظر بگیرید:

</div>

In [111]:
a = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


<div dir="rtl">

می‌توانید تابع `cumsum()` را برای به دست آوردن مجموع تجمعی عناصر فراخوانی کنید:

</div>

In [112]:
print(a.cumsum())   # prints the cumulative sum of all the
                    # elements in the array
                    # [ 1  3  6 10 15 21 28 36 45]


[ 1  3  6 10 15 21 28 36 45]


<div dir="rtl">

در این حالت، تابع `cumsum()` یک آرایه رتبه ۱ شامل مجموع تجمعی تمام عناصر در آرایه `a` را برمی‌گرداند. تابع `cumsum()` همچنین یک آرگومان اختیاری به نام `axis` می‌گیرد. مشخص کردن `axis=0` نشان می‌دهد که می‌خواهید مجموع تجمعی هر ستون را به دست آورید:

</div>

In [113]:
print(a.cumsum(axis=0))  # sum over rows for each of the 3 columns


[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


<div dir="rtl">

مشخص کردن `axis=1` نشان می‌دهد که می‌خواهید مجموع تجمعی هر سطر را به دست آورید:

</div>

In [114]:
print(a.cumsum(axis=1))  # sum over columns for each of the 3 rows


[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


<div dir="rtl">

---

## مرتب‌سازی در NumPy

NumPy تعدادی تابع مرتب‌سازی کارآمد ارائه می‌دهد که مرتب‌سازی یک آرایه را بسیار آسان می‌کند. اولین تابع برای مرتب‌سازی، `sort()` است که یک آرایه را می‌گیرد و یک آرایه مرتب شده را برمی‌گرداند. مثال زیر را در نظر بگیرید:

</div>

In [115]:
ages = np.array([34,12,37,5,13])
sorted_ages = np.sort(ages)   # does not modify the original array
print(sorted_ages)            # [ 5 12 13 34 37]
print(ages)                   # [34 12 37  5 13]


[ 5 12 13 34 37]
[34 12 37  5 13]


<div dir="rtl">

همانطور که از خروجی می‌بینید، تابع `sort()` آرایه اصلی را تغییر نمی‌دهد. در عوض، یک آرایه مرتب شده را برمی‌گرداند. اگر می‌خواهید آرایه اصلی را مرتب کنید، تابع `sort()` را روی خود آرایه فراخوانی کنید:

</div>

In [116]:
ages.sort()                   # modifies the array
print(ages)                   # [ 5 12 13 34 37]


[ 5 12 13 34 37]


<div dir="rtl">

تابع دیگری که برای مرتب‌سازی استفاده می‌شود، `argsort()` است. برای درک نحوه کار آن، بررسی مثال کد زیر مفید است:

</div>

In [117]:
ages = np.array([34,12,37,5,13])
print(ages.argsort())         # [3 1 4 0 2]


[3 1 4 0 2]


<div dir="rtl">

تابع `argsort()` اندیس‌هایی را برمی‌گرداند که یک آرایه را مرتب می‌کنند. در مثال بالا، اولین عنصر (3) در نتیجه تابع `argsort()` به این معنی است که کوچکترین عنصر پس از مرتب‌سازی در اندیس 3 آرایه اصلی قرار دارد که عدد 5 است. عدد بعدی در اندیس 1 قرار دارد که عدد 12 است، و به همین ترتیب.

برای چاپ آرایه `ages` مرتب شده، از نتیجه `argsort()` به عنوان اندیس آرایه `ages` استفاده کنید:

</div>

In [ ]:
print(ages[ages.argsort()])   # [ 5 12 13 34 37]


<div dir="rtl">

کاربرد واقعی `argsort()` چیست؟ تصور کنید که سه آرایه دارید که نشان‌دهنده لیستی از افراد، همراه با سن و قد آنهاست:

</div>

In [118]:
persons = np.array(['Johnny','Mary','Peter','Will','Joe'])
ages    = np.array([34,12,37,5,13])
heights = np.array([1.76,1.2,1.68,0.5,1.25])


<div dir="rtl">

فرض کنید می‌خواهید این گروه از افراد را بر اساس سن مرتب کنید. اگر فقط آرایه `ages` را به تنهایی مرتب کنید، دو آرایه دیگر بر اساس سن به درستی مرتب نمی‌شوند. اینجاست که `argsort()` واقعاً به کار می‌آید:

</div>

In [119]:
sort_indices = np.argsort(ages)  # performs a sort based on ages
                                 # and returns an array of indices
                                 # indicating the sort order


<div dir="rtl">

پس از به دست آوردن اندیس‌های مرتب‌سازی، آنها را به سه آرایه وارد کنید:

</div>

In [120]:
print(persons[sort_indices])      # ['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
print(ages[sort_indices])         # [ 5 12 13 34 37]
print(heights[sort_indices])      # [ 0.5   1.2   1.25  1.76  1.68]


['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]


<div dir="rtl">

اکنون آنها بر اساس سن مرتب شده‌اند. همانطور که می‌بینید، ویل جوان‌ترین است، پس از آن مری، و به همین ترتیب. قد متناظر برای هر فرد نیز به ترتیب صحیح خواهد بود.

اگر می‌خواهید بر اساس نام مرتب کنید، به سادگی از `argsort()` روی آرایه `persons` استفاده کنید و اندیس‌های حاصل را به سه آرایه وارد کنید:

</div>

In [ ]:
sort_indices = np.argsort(persons)   # sort based on names
print(persons[sort_indices])         # ['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
print(ages[sort_indices])            # [13 34 12 37  5]
print(heights[sort_indices])         # [ 1.25  1.76  1.2   1.68  0.5 ]


<div dir="rtl">

برای معکوس کردن ترتیب نام‌ها و نمایش آنها به ترتیب نزولی، از نماد پایتون `[::-1]` استفاده کنید:

</div>

In [ ]:
reverse_sort_indices = np.argsort(persons)[::-1] # reverse the order of a list
print(persons[reverse_sort_indices])     # ['Will' 'Peter' 'Mary' 'Johnny' 'Joe']
print(ages[reverse_sort_indices])        # [ 5 37 12 34 13]
print(heights[reverse_sort_indices])     # [ 0.5   1.68  1.2   1.76  1.25]


<div dir="rtl">

---

# انتساب آرایه (Array Assignment)

هنگام انتساب آرایه‌های NumPy، باید به نحوه انتساب آرایه‌ها توجه کنید. در ادامه تعدادی مثال برای توضیح این موضوع آورده شده است.

### کپی با مرجع (Copying by Reference)

آرایه‌ای به نام `a1` را در نظر بگیرید:

</div>

In [121]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
print(a1)


[[1 2 3 4]
 [5 6 7 8]]


In [122]:
a2 = a1             # creates a copy by reference
print(a1)
print(a2)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [124]:
a1[1][1] = 25     # make some changes to a2
print(a1)          # affects a1
print(a2)


[[11  2  3  4]
 [ 5 25  7  8]]
[[11  2  3  4]
 [ 5 25  7  8]]


In [125]:
a1.shape = 1,-1   # reshape a1
print(a1)
print(a2)         # a2 also changes shape


[[11  2  3  4  5 25  7  8]]
[[11  2  3  4  5 25  7  8]]


<div dir="rtl">

### کپی برحسب نما(کپی کم عمق) 

NumPy تابع `view()` دارد که به شما امکان می‌دهد یک کپی از یک آرایه را با مرجع ایجاد کنید، در حالی که همزمان تضمین می‌کند که تغییر شکل آرایه اصلی روی شکل کپی تأثیر نمی‌گذارد. این به عنوان یک **کپی سطحی** شناخته می‌شود. بیایید به یک مثال نگاه کنیم تا نحوه کار آن را درک کنیم:

</div>

In [126]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
a2 = a1.view()    # creates a copy of a1 by reference; but changes
                  # in dimension in a1 will not affect a2
print(a1)
print(a2)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [127]:
a1[0][0] = 11     # make some changes in a1
print(a1)
print(a2)         # changes is also seen in a2


[[11  2  3  4]
 [ 5  6  7  8]]
[[11  2  3  4]
 [ 5  6  7  8]]


In [128]:
a1.shape = 1,-1   # change the shape of a1
# a1 = a1.reshape(1,-1)
print(a1)
print(a2)         # a2 does not change shape


[[11  2  3  4  5  6  7  8]]
[[11  2  3  4]
 [ 5  6  7  8]]


<div dir="rtl">

تا اینجا، کپی سطحی مشابه کپی انجام شده در بخش قبل است. اما با کپی سطحی، وقتی شکل `a1` را تغییر می‌دهید، `a2` تحت تأثیر قرار نمی‌گیرد.

### کپی با مقدار (Deep Copy)

اگر می‌خواهید یک آرایه را با مقدار کپی کنید، از تابع `copy()` استفاده کنید، مانند مثال زیر:

</div>

In [129]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
a2 = a1.copy()     # create a copy of a1 by value (deep copy)


<div dir="rtl">

تابع `copy()` یک کپی عمیق از آرایه ایجاد می‌کند - یک کپی کامل از آرایه و داده‌های آن ایجاد می‌کند. وقتی کپی آرایه را به متغیر دیگری اختصاص می‌دهید، هر تغییری در شکل آرایه اصلی روی کپی آن تأثیر نخواهد گذاشت. در اینجا اثبات آن آورده شده است:

</div>

In [130]:
a1[0][0] = 11     # make some changes in a1
print(a1)
print(a2)         # changes is not seen in a2


[[11  2  3  4]
 [ 5  6  7  8]]
[[1 2 3 4]
 [5 6 7 8]]


In [131]:
a1.shape = 1,-1   # change the shape of a1
print(a1)
print(a2)         # a2 does not change shape

[[11  2  3  4  5  6  7  8]]
[[1 2 3 4]
 [5 6 7 8]]


<div dir="rtl">

---

## خلاصه

در این فصل، با استفاده از NumPy به عنوان راهی برای نمایش داده‌های هم نوع آشنا شدید. همچنین یاد گرفتید که چگونه آرایه‌هایی با ابعاد مختلف ایجاد کنید و همچنین چگونه به داده‌های ذخیره شده درون آرایه‌ها دسترسی پیدا کنید. یکی از ویژگی‌های مهم آرایه‌های NumPy توانایی آنها در انجام محاسبات ریاضی آرایه به راحتی و کارآمدی است، بدون اینکه نیاز به نوشتن کدهای زیاد داشته باشید.

در فصل بعد، با کتابخانه مهم دیگری آشنا خواهید شد که کار با داده‌های جدولی را آسان می‌کند - **Pandas**.

</div>